### ISSUE TITLE
ActionController::InvalidAuthenticityToken When trying to create a new account 

### ISSUE THREAD

**Issue by kainio** [socializer/socializer#210]
In a fresh installation of socializer, I can't create a new account, I got an error linked to (handle_unverified_request) actionpack (5.1.4) lib/action_controller/metal/request_forgery_protection.rb

**Comment by acmetech** [comment]
Hi @kainio,

Would you be able to provide more details? Did you add the gem to your gemfile using the instructions from the readme or from rubygems.org?

Thanks

**Comment by kainio** [comment]
Thanks @acmetech  for your reply.
I used this github repo in my Gemfile as described in the readme.

**Comment by acmetech** [comment]
@kainio, Do you have the same issue if you download the socializer/socializer_test app?

Thanks

**Comment by kainio** [comment]
I got the same issue when trying with the socializer_test
in the logs i got this error

> Can't verify CSRF token authenticity.


I am using rails 5.1.4 and sqlite

**Comment by acmetech** [comment]
@kainio, I've pushed a temporary solution. Please update socializer and give it a try

**Comment by kainio** [comment]
@acmetech, It's working now thanks.

**Comment by acmetech** [comment]
Glad that did it for you. You're welcome
